theme: jekyll-theme-minimal
title: Design in Safaries - Sonia Zhang's Portfolio
description: I am an anthropology student trying to make sense of interaction design for animals. Still working on how to make this look less like a plain word document.

